module.exports = app => {
  app.redirect('/chiquito-experience/', '/', 301);
  app.redirect(/^\/blog\/.*/, '/', 301);
  app.redirect('/join-us', 'https://harri.com/Chiquito', 301);
  app.redirect('/contact-us', '/contact', 301);
  app.redirect('/terms-and-conditions', '/terms', 301);
  app.redirect('/pay-my-bill-terms', '/terms', 301);
  app.redirect('/privacy-policy', '/terms');
  app.redirect('/contact-us', '/contact', 301);
  app.redirect('/charity', '/', 301);
  app.redirect('/my-chiquito', '/offers/profile', 301);
  app.redirect('/menus', '/nearest-me/menu', 301);
  app.redirect(/^\/claim-your-voucher.*/, '/offers/profile', 301);
  app.redirect(/^\/[a-z-]+menu.*/, '/menu', 301);
  app.redirect(/^\/.*allergy-advice.*/, '/menu', 301);
  app.redirect(/^\/find_a_restaurant.*/, '/nearest-me', 301);
  app.redirect('/restaurants/search', '/nearest-me', 301);
  app.redirect(
    '/restaurants/london/london/london-leicester-square',
    '/restaurants/london-leicester-square',
    301
  );
  app.redirect(
    '/restaurants/east-of-england/hatfield/hatfield',
    '/restaurants/hatfield',
    301
  );
  app.redirect(
    '/restaurants/west-midlands/coventry/coventry',
    '/restaurants/coventry',
    301
  );
  app.redirect(
    '/restaurants/scotland/aberdeen/aberdeen-union-square',
    '/restaurants/aberdeen-union-square',
    301
  );
  app.redirect(
    '/restaurants/south-east/crawley/crawley',
    '/restaurants/crawley',
    301
  );
  app.redirect(
    '/restaurants/east-of-england/stevenage/stevenage',
    '/restaurants/stevenage',
    301
  );
  app.redirect(
    '/restaurants/south-west/plymouth/plymouth',
    '/restaurants/plymouth',
    301
  );
  app.redirect(
    '/restaurants/london/london/london-o2',
    '/restaurants/london-o2',
    301
  );
  app.redirect(
    '/restaurants/east-of-england/huntingdon/huntingdon',
    '/restaurants/huntingdon',
    301
  );
  app.redirect(
    '/restaurants/south-east/milton-keynes/milton-keynes-kingston-centre',
    '/restaurants/milton-keynes-kingston-centre',
    301
  );
  app.redirect(
    '/restaurants/west-midlands/exeter/exeter',
    '/restaurants/exeter',
    301
  );
  app.redirect(
    '/restaurants/east-of-england/hemel-hempstead/hemel-hempstead',
    '/restaurants/hemel-hempstead',
    301
  );
  app.redirect(
    '/restaurants/east-midlands/mansfield/mansfield',
    '/restaurants/mansfield',
    301
  );
  app.redirect(
    '/restaurants/west-midlands/shrewsbury/shrewsbury',
    '/restaurants/shrewsbury',
    301
  );
  app.redirect(
    '/restaurants/scotland/edinburgh/kinnaird-park',
    '/restaurants/kinnaird-park',
    301
  );
  app.redirect(
    '/restaurants/north-west/crewe/crewe',
    '/restaurants/crewe',
    301);
  app.redirect(
    '/restaurants/london/uxbridge/uxbridge',
    '/restaurants/uxbridge',
    301
  );
  app.redirect(
    '/restaurants/south-west/trowbridge/trowbridge',
    '/restaurants/trowbridge',
    301
  );
  app.redirect(
    '/restaurants/west-midlands/walsall/walsall-0',
    '/restaurants/walsall-0',
    301
  );
  app.redirect(
    '/restaurants/wales/llantrisant/llantrisant',
    '/restaurants/llantrisant',
    301
  );
  app.redirect(
    '/restaurants/north-east/durham/durham-walkergate',
    '/restaurants/durham-walkergate',
    301
  );
  app.redirect(
    '/restaurants/east-midlands/chesterfield/chesterfield',
    '/restaurants/chesterfield',
    301
  );
  app.redirect(
    '/restaurants/wales/newport/newport',
    '/restaurants/newport',
    301
  );
  app.redirect(
    '/restaurants/yorkshire-and-the-humber/leeds/leeds-white-rose-shopping-centre',
    '/restaurants/leeds-%E2%80%93-white-rose-shopping-centre',
    301
  );
  app.redirect(
    '/restaurants/west-midlands/wolverhampton/wolverhampton',
    '/restaurants/wolverhampton',
    301
  );
  app.redirect(
    '/restaurants/east-of-england/harlow/harlow',
    '/restaurants/harlow',
    301
  );
  app.redirect(
    '/restaurants/scotland/edinburgh/edinburgh-fountain-park',
    '/restaurants/edinburgh-fountain-park',
    301
  );
  app.redirect(
    '/restaurants/south-west/poole/poole',
    '/restaurants/poole',
    301
  );
  app.redirect(
    '/restaurants/south-west/truro/truro',
    '/restaurants/truro',
    301
  );
  app.redirect(
    '/restaurants/scotland/east-kilbride/east-kilbride',
    '/restaurants/east-kilbride',
    301
  );
  app.redirect(
    '/restaurants/south-west/bournemouth/bournemouth',
    '/restaurants/bournemouth',
    301
  );
  app.redirect(
    '/restaurants/london/london/enfield',
    '/restaurants/enfield',
    301
  );
  app.redirect(
    '/restaurants/london/london/south-ruislip',
    '/restaurants/south-ruislip',
    301
  );
  app.redirect(
    '/restaurants/east-of-england/basildon/basildon',
    '/restaurants/basildon',
    301
  );
  app.redirect(
    '/restaurants/south-west/bristol/bristol-aspects',
    '/restaurants/bristol-aspects',
    301
  );
  app.redirect(
    '/restaurants/yorkshire-and-the-humber/hull/hull-kingswood',
    '/restaurants/hull-kingswood',
    301
  );
  app.redirect(
    '/restaurants/london/london/london-park-royal',
    '/restaurants/london-park-royal',
    301
  );
  app.redirect(
    '/restaurants/south-east/ashford/ashford',
    '/restaurants/ashford',
    301
  );
  app.redirect(
    '/restaurants/london/croydon/croydon',
    '/restaurants/croydon',
    301
  );
  app.redirect(
    '/restaurants/south-east/thanet/thanet',
    '/restaurants/thanet',
    301
  );
  app.redirect(
    '/restaurants/east-of-england/watford/watford',
    '/restaurants/watford',
    301
  );
  app.redirect(
    '/restaurants/scotland/dunfermline/dunfermline',
    '/restaurants/dunfermline',
    301
  );
  app.redirect(
    '/restaurants/north-east/stockton/stockton',
    '/restaurants/stockton',
    301
  );
  app.redirect(
    '/restaurants/yorkshire-and-the-humber/manchester/salford-quays',
    '/restaurants/salford-quays',
    301
  );
  app.redirect(
    '/restaurants/west-midlands/birmingham/birmingham-hagley-road',
    '/restaurants/birmingham-hagley-road',
    301
  );
  app.redirect(
    '/restaurants/east-of-england/norwich/norwich',
    '/restaurants/norwich',
    301
  );
  app.redirect(
    '/restaurants/east-midlands/derby/derby',
    '/restaurants/derby',
    301
  );
  app.redirect(
    '/restaurants/east-of-england/colchester/colchester',
    '/restaurants/colchester',
    301
  );
  app.redirect(
    '/restaurants/yorkshire-and-the-humber/york/york-clifton-moor-leisure',
    '/restaurants/york-clifton-moor-leisure',
    301
  );
  app.redirect(
    '/restaurants/scotland/glasgow/glasgow-fort',
    '/restaurants/glasgow-fort',
    301
  );
  app.redirect(
    '/restaurants/scotland/aberdeen/aberdeen-beach',
    '/restaurants/aberdeen-beach',
    301
  );
  app.redirect(
    '/restaurants/east-midlands/nottingham/nottingham-cornerhouse',
    '/restaurants/nottingham-cornerhouse',
    301
  );
  app.redirect(
    '/restaurants/south-west/swindon/swindon',
    '/restaurants/swindon',
    301
  );
  app.redirect(
    '/restaurants/west-midlands/rubery/birmingham-rubery',
    '/restaurants/birmingham-rubery',
    301
  );
  app.redirect(
    '/restaurants/london/feltham/feltham',
    '/restaurants/feltham',
    301
  );
  app.redirect(
    '/restaurants/scotland/renfrew/braehead',
    '/restaurants/braehead',
    301
  );
  app.redirect(
    '/restaurants/south-east/southampton/southampton',
    '/restaurants/southampton',
    301
  );
  app.redirect(
    '/restaurants/yorkshire-and-the-humber/castleford/castleford-xscape',
    '/restaurants/castleford-xscape',
    301
  );
  app.redirect(
    '/restaurants/north-west/southport/southport',
    '/restaurants/southport',
    301
  );
  app.redirect(
    '/restaurants/north-west/preston/preston',
    '/restaurants/preston',
    301
  );
  app.redirect(
    '/restaurants/north-west/manchester/didsbury',
    '/restaurants/didsbury',
    301
  );
  app.redirect(
    '/restaurants/south-west/cheltenham/cheltenham-brewery',
    '/restaurants/cheltenham-brewery',
    301
  );
  app.redirect(
    '/restaurants/east-of-england/cambridge/cambridge-leisure-park',
    '/restaurants/cambridge-leisure-park',
    301
  );
  app.redirect(
    '/restaurants/leicester',
    '/restaurants/east-midlands/leicester/leicester',
    301
  );
  app.redirect(
    '/restaurants/nottingham-lenton',
    '/restaurants/west-midlands/nottingham/nottingham-lenton',
    301
  );
  app.redirect(
    'restaurants/sheffield',
    'restaurants/yorkshire-and-the-humber/sheffield/sheffield',
    301
  );
  app.redirect(
    'restaurants/stoke',
    'restaurants/west-midlands/stoke-on-trent/stoke',
    301
  );
  app.redirect(
    '/restaurants/manchester-printworks',
    '/restaurants/north-west/manchester/manchester-printworks',
    301
  );
  app.redirect(
    '/restaurants/ashton-moss',
    '/restaurants/yorkshire-and-the-humber/ashton-under-lyne/ashton-moss',
    301
  );
  app.redirect(
    '/restaurants/bolton',
    '/restaurants/north-west/bolton/bolton',
    301
  );
  app.redirect(
    '/restaurants/leeds-centre-27',
    '/restaurants/yorkshire-and-the-humber/leeds/leeds-centre-27',
    301
  );
  app.redirect(
    '/restaurants/northampton',
    '/restaurants/east-midlands/northampton/northampton',
    301
  );
  app.redirect(
    '/restaurants/peterborough-hampton',
    '/restaurants/east-of-england/peterborough/peterborough-hampton',
    301
  );
  app.redirect(
    '/restaurants/rochester',
    '/restaurants/south-east/strood/rochester',
    301
  );
  app.redirect(
    '/restaurants/camberley-atrium',
    '/restaurants/south-east/camberley/camberley-atrium',
    301
  );
  app.redirect(
    '/restaurants/portsmouth-gunwharf-quay',
    '/restaurants/south-east/portsmouth/portsmouth-gunwharf-quay',
    301
  );
  app.redirect(
    '/restaurants/cribbs-causeway-venue',
    '/restaurants/south-west/bristol/cribbs-causeway-venue',
    301
  );
  app.redirect(
    '/restaurants/dudley',
    '/restaurants/west-midlands/dudley/dudley',
    301
  );
  app.redirect(
    '/restaurants/ipswich',
    '/restaurants/east-of-england/ipswich/ipswich',
    301
  );
  app.redirect(
    '/restaurants/gateshead',
    '/restaurants/north-east/gateshead/gateshead',
    301
  );
  app.redirect(
    '/restaurants/newcastle-eldon-square',
    '/restaurants/north-east/newcastle/newcastle-eldon-square',
    301
  );
  app.redirect(
    'restaurants/cheshire-oaks',
    '/restaurants/north-west/ellesmere-port/cheshire-oaks',
    301
  );
  app.redirect(
    '/restaurants/liverpool-edge-lane',
    '/restaurants/north-west/liverpool/liverpool-edge-lane',
    301
  );
  app.redirect(
    '/restaurants/livingston',
    '/restaurants/scotland/livingston/livingston',
    301
  );
  app.redirect(
    '/restaurants/chester',
    '/restaurants/wales/broughton/chester',
    301
  );
  app.redirect('/click-and-collect', '/takeaway', 301);
  app.redirect('/menu/festive', '/christmas', 301);
  app.redirect('/dora', 'https://www.whippersnapperkids.com/dora', 301);
};
